---
title: Exploratory Analysis of Red Wine Data
author: Daniel Dulaney
date: October 31, 2020 
output: github_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r, message=FALSE}
library(tidyverse)
library(here)
library(skimr)
library(ggcorrplot)
library(kableExtra)
```

```{r}
red_wine <- read_csv(here("final-project", "red_wine.csv")) %>% 
  # replace spaces in variable names with underscores
  janitor::clean_names()
```

```{r}
skim(red_wine)
```

```{r}
red_wine %>% 
  pivot_longer(cols = everything(), names_to = "property") %>% 
  ggplot(aes(value, fill = property)) +
  geom_histogram(bins = 25) +
  facet_wrap(~property, scales = "free") +
  ggeasy::easy_remove_legend() +
  labs(title = "Distribution of each variable in the dataset")
```

```{r}
# count of Quality ratings?
red_wine %>%
  count(quality) %>%
  mutate(freq = n / sum(n),
         freq = round(freq, 2)) %>% 
  kable(caption = "Frequency of quality ratings") %>% 
  kable_styling(full_width = FALSE, bootstrap_options = "striped")
```

```{r}
# calculate correlations between properties and quality
cors <- red_wine %>% 
  cor() %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  select(rowname, quality) %>% 
  rename(cor_to_quality = quality,
         property = rowname)

# scatterplots, where facets are ordered from highest to lowest correlation with quality
red_wine %>% 
  pivot_longer(cols = fixed_acidity:alcohol, names_to = "property") %>% 
  inner_join(cors, by = "property") %>%
  mutate(property = fct_reorder(property, abs(cor_to_quality), .desc = TRUE)) %>% 
  ggplot(aes(quality, value, color = property)) +
  geom_point(alpha = .075) +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~property, scales = "free") +
  ggeasy::easy_remove_legend() +
  labs(title = "Relationship between quality and each variable in the dataset",
       y = "value_of_var")
```

This tell us that of the higher rated wines, `alcohol` had high values and `volatile_acidity` had low values.

```{r}
# check correlation between variables-- any signs of multicollinearity?
red_wine %>% 
  cor() %>% 
  ggcorrplot(title = "Linear relationships between red wine dataset variables", 
             type = "lower", hc.order = TRUE, lab = TRUE, lab_size = 2.5)
```




